// GENERATED by scripts/buildSongText.mjs from the client's
// pages/daloskonyv/chordpro.ts, chords.ts, chord-shapes.ts and keys.ts -
// the comments are there. Do not edit: change those and run the script.

// ../client/src/app/pages/daloskonyv/chordpro.ts
var DIRECTIVE = /^\{\s*([^:}]+?)\s*(?::\s*(.*?)\s*)?\}$/;
var SECTION_MARKS = {
  start_of_chorus: { type: 'section-start', section: 'chorus' },
  soc: { type: 'section-start', section: 'chorus' },
  end_of_chorus: { type: 'section-end', section: 'chorus' },
  eoc: { type: 'section-end', section: 'chorus' },
  start_of_verse: { type: 'section-start', section: 'verse' },
  sov: { type: 'section-start', section: 'verse' },
  end_of_verse: { type: 'section-end', section: 'verse' },
  eov: { type: 'section-end', section: 'verse' },
};
function parseChordPro(source) {
  const song = { lines: [] };
  for (const raw of source.replace(/\r\n?/g, '\n').split('\n')) {
    const line = raw.trimEnd();
    if (!line.trim()) {
      song.lines.push({ type: 'empty' });
      continue;
    }
    const directive = DIRECTIVE.exec(line.trim());
    if (directive) {
      const name = directive[1].toLowerCase();
      const value = directive[2] ?? '';
      if (name === 'title' || name === 't') song.title = value;
      else if (name === 'artist') song.artist = value;
      else if (name === 'comment' || name === 'c')
        song.lines.push({ type: 'comment', text: value });
      else if (SECTION_MARKS[name]) song.lines.push(SECTION_MARKS[name]);
      continue;
    }
    const segments = parseLine(line);
    const chordsOnly = segments.every((s) => !s.text.trim()) && segments.some((s) => s.chord);
    song.lines.push({ type: chordsOnly ? 'chords-only' : 'lyrics', segments });
  }
  return song;
}
function parseLine(line) {
  const segments = [];
  const chord = /\[([^\]]*)\]/g;
  let from = 0;
  let current = { text: '' };
  for (let m = chord.exec(line); m; m = chord.exec(line)) {
    current.text = line.slice(from, m.index);
    if (current.chord !== void 0 || current.text) segments.push(current);
    current = { chord: m[1].trim(), text: '' };
    from = m.index + m[0].length;
  }
  current.text = line.slice(from);
  if (current.chord !== void 0 || current.text) segments.push(current);
  return segments;
}
function toBlocks(lines) {
  const blocks = [];
  let inChorus = false;
  let current = null;
  const close = () => {
    if (current?.lines.length) blocks.push(current);
    current = null;
  };
  for (const line of lines) {
    if (line.type === 'empty') close();
    else if ('section' in line) {
      close();
      if (line.section === 'chorus') inChorus = line.type === 'section-start';
    } else {
      current ??= { chorus: inChorus, lines: [] };
      current.lines.push(line);
    }
  }
  close();
  return blocks;
}
function toWords(segments) {
  const words = [];
  let open2 = false;
  const add = (piece) => {
    if (open2) words[words.length - 1].push(piece);
    else words.push([piece]);
    open2 = piece.text !== '' && !/\s$/.test(piece.text);
  };
  for (const segment of segments) {
    const tokens = segment.text.match(/\S+\s*|\s+/g) ?? [];
    if (segment.chord !== void 0) {
      const first = tokens[0] && /\S/.test(tokens[0]) ? tokens.shift() : '';
      add({ chord: segment.chord, text: first });
    }
    for (const token of tokens) add({ text: token });
  }
  return words;
}

// ../client/src/app/pages/daloskonyv/chords.ts
var NOTATION = 'hungarian';
var SHARPS = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'A#', 'B'];
var FLATS = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'Bb', 'B'];
var NATURAL = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11, H: 11 };
var CHORD = /^([A-Ha-h])([#b]?)([^/]*)(?:\/([A-Ha-h])([#b]?))?$/;
var REST = /^(?:maj|min|dim|aug|sus|add|m|M|[0-9+\-°ø()#b,])*$/;
function pitch(letter, accidental, notation) {
  const note = letter.toUpperCase();
  if (note === 'B' && !accidental && notation === 'hungarian') return 10;
  const shift = accidental === '#' ? 1 : accidental === 'b' ? -1 : 0;
  return (NATURAL[note] + shift + 12) % 12;
}
function parseChord(name, notation = NOTATION) {
  const m = CHORD.exec(name.trim());
  if (!m || !REST.test(m[3])) return null;
  const rest = m[3];
  const lower = m[1] !== m[1].toUpperCase();
  return {
    root: pitch(m[1], m[2], notation),
    minor: lower || (rest.startsWith('m') && !rest.startsWith('maj')),
    rest,
    bass: m[4] ? pitch(m[4], m[5], notation) : null,
    lower,
  };
}
function noteName(pc, flats, notation) {
  if (notation === 'hungarian') {
    if (pc === 11) return 'H';
    if (pc === 10) return 'B';
  }
  return (flats ? FLATS : SHARPS)[pc];
}
var FLAT_KEYS = /* @__PURE__ */ new Set([5, 10, 3, 8, 1]);
function keyUsesFlats(root, minor) {
  return FLAT_KEYS.has(minor ? (root + 3) % 12 : root);
}
function transposer(firstChord, steps, notation = NOTATION) {
  const by = ((steps % 12) + 12) % 12;
  if (!by) return (chord) => chord;
  const key = firstChord ? parseChord(firstChord, notation) : null;
  const flats = key ? keyUsesFlats((key.root + by) % 12, key.minor) : false;
  return (name) => {
    const chord = parseChord(name, notation);
    if (!chord) return name;
    const note = (pc) => noteName((pc + by) % 12, flats, notation);
    const root = chord.lower ? note(chord.root).toLowerCase() : note(chord.root);
    return root + chord.rest + (chord.bass === null ? '' : `/${note(chord.bass)}`);
  };
}

// ../client/src/app/pages/daloskonyv/chord-shapes.ts
var open = (root, frets) => ({ root, frets });
var movable = (root, frets, period) => ({
  root,
  frets,
  movable: true,
  period,
});
var [C, D, E, F, G, A, H] = [0, 2, 4, 5, 7, 9, 11];
var GUITAR = {
  maj: [
    open(C, 'x32010'),
    open(D, 'xx0232'),
    open(G, '320003'),
    movable(E, '022100'),
    movable(A, 'x02220'),
  ],
  m: [open(D, 'xx0231'), movable(E, '022000'), movable(A, 'x02210')],
  7: [
    open(C, 'x32310'),
    open(D, 'xx0212'),
    open(G, '320001'),
    open(H, 'x21202'),
    movable(E, '020100'),
    movable(A, 'x02020'),
  ],
  m7: [open(D, 'xx0211'), movable(E, '020000'), movable(A, 'x02010')],
  maj7: [
    open(C, 'x32000'),
    open(D, 'xx0222'),
    open(F, 'xx3210'),
    open(G, '320002'),
    movable(E, '021100'),
    movable(A, 'x02120'),
  ],
  sus4: [
    open(C, 'x33011'),
    open(D, 'xx0233'),
    open(G, '330013'),
    movable(E, '022200'),
    movable(A, 'x02230'),
  ],
  sus2: [open(D, 'xx0230'), movable(A, 'x02200')],
  6: [
    open(C, 'x32210'),
    open(D, 'xx0202'),
    open(G, '320000'),
    movable(E, '022120'),
    movable(A, 'x02222'),
  ],
  9: [open(D, 'xx0210'), movable(E, '020102'), movable(A, 'x02423')],
  add9: [open(C, 'x32030'), open(G, '320203'), open(D, 'xx0230'), movable(A, 'x02420')],
  dim: [movable(A, 'x0121x'), movable(D, 'xx0101')],
  aug: [movable(E, '032110'), movable(A, 'x03221')],
};
var UKULELE = {
  maj: [
    movable(C, '0003'),
    movable(D, '2220'),
    movable(F, '2010'),
    movable(G, '0232'),
    movable(A, '2100'),
  ],
  m: [
    movable(C, '0333'),
    movable(D, '2210'),
    movable(E, '0432'),
    movable(F, '1013'),
    movable(6, '2120'),
    movable(G, '0231'),
    movable(A, '2000'),
  ],
  7: [
    movable(C, '0001'),
    movable(D, '2223'),
    movable(E, '1202'),
    movable(F, '2313'),
    movable(G, '0212'),
    movable(A, '0100'),
  ],
  m7: [movable(D, '2213'), movable(E, '0202'), movable(G, '0211'), movable(A, '0000')],
  maj7: [
    movable(C, '0002'),
    movable(D, '2224'),
    movable(F, '2413'),
    movable(G, '0222'),
    movable(A, '1100'),
  ],
  sus4: [
    movable(C, '0013'),
    movable(D, '0230'),
    movable(F, '3011'),
    movable(G, '0233'),
    movable(A, '2200'),
  ],
  sus2: [movable(C, '0233'), movable(D, '2200'), movable(F, '0013'), movable(G, '0230')],
  6: [movable(C, '0000'), movable(D, '2222'), movable(F, '2213'), movable(G, '0202')],
  9: [movable(C, '0201'), movable(D, '2424'), movable(G, '2212'), movable(A, '0102')],
  add9: [movable(C, '0203'), movable(F, '0010'), movable(G, '0252')],
  // The ukulele's "dim" is the four-note one: the same shape every 3 frets.
  dim: [movable(1, '0101', 3)],
  // The same shape every 4 frets.
  aug: [movable(3, '0332', 4), movable(C, '1003', 4)],
};
var SHAPES = {
  guitar: GUITAR,
  ukulele: UKULELE,
};
function quality(rest, minor) {
  let r = rest.replace(/[()]/g, '');
  if (minor && !r.startsWith('m')) r = `m${r}`;
  if (r === '-') return 'm';
  if (/^(dim7?|0|°|m7b5|ø)/.test(r)) return 'dim';
  if (/^(aug|\+)/.test(r)) return 'aug';
  if (/^(maj|M)/.test(r)) return 'maj7';
  if (/^m(in)?/.test(r)) return /^m(in)?(7|9|11)/.test(r) ? 'm7' : 'm';
  if (/^(sus4|sus$|4)/.test(r)) return 'sus4';
  if (/^(sus2|2)/.test(r)) return 'sus2';
  if (/^add9/.test(r)) return 'add9';
  if (/^9/.test(r)) return '9';
  if (/^6/.test(r)) return '6';
  if (/^(7|11|13)/.test(r)) return '7';
  return 'maj';
}
var fretsOf = (t) => [...t.frets].map((f) => (f === 'x' ? -1 : Number(f)));
function chordShape(name, instrument, notation = NOTATION) {
  const chord = parseChord(name, notation);
  if (!chord) return null;
  const templates = SHAPES[instrument][quality(chord.rest, chord.minor)];
  let best = null;
  let bestTop = Infinity;
  let bestUp = Infinity;
  for (const template of templates) {
    const up = ((chord.root - template.root + 12) % 12) % (template.period ?? 12);
    if (up && !template.movable) continue;
    const base = fretsOf(template);
    const frets = base.map((f) => (f < 0 ? f : f + up));
    const top = Math.max(...frets);
    if (top > bestTop || (top === bestTop && up >= bestUp)) continue;
    const held = base.flatMap((f, i) => (f === 0 ? [i] : []));
    bestTop = top;
    bestUp = up;
    best = {
      frets,
      barre: up && held.length > 1 ? { fret: up, from: held[0], to: held[held.length - 1] } : null,
    };
  }
  return best;
}
function uniqueChords(chords, notation = NOTATION) {
  const seen = /* @__PURE__ */ new Set();
  return chords.filter((name) => {
    if (seen.has(name) || !parseChord(name, notation)) return false;
    seen.add(name);
    return true;
  });
}

// ../client/src/app/pages/daloskonyv/keys.ts
var CIRCLE = [
  { major: ['C'], minor: ['am'], signs: ['0'] },
  { major: ['G'], minor: ['em'], signs: ['1 #'] },
  { major: ['D'], minor: ['hm'], signs: ['2 #'] },
  { major: ['A'], minor: ['f#m'], signs: ['3 #'] },
  { major: ['E'], minor: ['c#m'], signs: ['4 #'] },
  { major: ['H'], minor: ['g#m'], signs: ['5 #'] },
  { major: ['F#', 'Gb'], minor: ['d#m', 'ebm'], signs: ['6 #', '6 b'] },
  { major: ['Db'], minor: ['bm'], signs: ['5 b'] },
  { major: ['Ab'], minor: ['fm'], signs: ['4 b'] },
  { major: ['Eb'], minor: ['cm'], signs: ['3 b'] },
  { major: ['B'], minor: ['gm'], signs: ['2 b'] },
  { major: ['F'], minor: ['dm'], signs: ['1 b'] },
];
var DEGREES = [
  { roman: 'I', semitones: 0, kind: 'major' },
  { roman: 'ii', semitones: 2, kind: 'minor' },
  { roman: 'iii', semitones: 4, kind: 'minor' },
  { roman: 'IV', semitones: 5, kind: 'major' },
  { roman: 'V', semitones: 7, kind: 'major' },
  { roman: 'vi', semitones: 9, kind: 'minor' },
  { roman: 'vii\xB0', semitones: 11, kind: 'dim' },
];
var SHARP_NOTES = ['C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#', 'A', 'B', 'H'];
var FLAT_NOTES = ['C', 'Db', 'D', 'Eb', 'E', 'F', 'Gb', 'G', 'Ab', 'A', 'B', 'H'];
var TABLE_KEYS = [
  { root: 0, flats: false },
  { root: 7, flats: false },
  { root: 2, flats: false },
  { root: 9, flats: false },
  { root: 4, flats: false },
  { root: 11, flats: false },
  { root: 6, flats: false },
  { root: 1, flats: true },
  { root: 8, flats: true },
  { root: 3, flats: true },
  { root: 10, flats: true },
  { root: 5, flats: true },
];
function keyChords() {
  return TABLE_KEYS.map(({ root, flats }) => {
    const notes = flats ? FLAT_NOTES : SHARP_NOTES;
    const chords = DEGREES.map(({ semitones, kind }) => {
      const note = notes[(root + semitones) % 12];
      if (kind === 'major') return note;
      return `${note.toLowerCase()}${kind === 'minor' ? 'm' : '\xB0'}`;
    });
    return { key: notes[root], chords };
  });
}
export {
  CIRCLE,
  DEGREES,
  NOTATION,
  chordShape,
  keyChords,
  parseChord,
  parseChordPro,
  toBlocks,
  toWords,
  transposer,
  uniqueChords,
};
