// The Daloskönyv's text logic - reading ChordPro, chord names, how a chord
// is held, the keys and their chords - is written once, in the client
// (TypeScript: client/src/app/pages/daloskonyv/chordpro.ts, chords.ts,
// chord-shapes.ts, keys.ts). The server needs the same for the songbook's
// PDF (src/songs/songBook.js), so this turns those files into one plain
// JS module:
//   node scripts/buildSongText.mjs
// Run it again whenever one of them changes, and commit the result.
import { execSync } from 'child_process';
import esbuild from 'esbuild';

const client = '../client/src/app/pages/daloskonyv';
const outfile = 'src/songs/songText.js';

await esbuild.build({
  stdin: {
    contents: `
      export { parseChordPro, toBlocks, toWords } from './chordpro';
      export { chordNamePieces, parseChord, transposer, NOTATION } from './chords';
      export { chordShape, uniqueChords } from './chord-shapes';
      export { CIRCLE, DEGREES, keyChords } from './keys';
    `,
    resolveDir: client,
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile,
  banner: {
    js: [
      "// GENERATED by scripts/buildSongText.mjs from the client's",
      '// pages/daloskonyv/chordpro.ts, chords.ts, chord-shapes.ts and keys.ts -',
      '// the comments are there. Do not edit: change those and run the script.',
    ].join('\n'),
  },
});
execSync(`npx prettier --write ${outfile} --ignore-path ../.prettierignore`, { stdio: 'inherit' });
console.log(`✓ ${outfile}`);
