// The Daloskönyv's text logic - reading ChordPro, chord names, how a chord
// is held - is written once, in the client (TypeScript:
// client/src/app/pages/daloskonyv/chordpro.ts, chords.ts, chord-shapes.ts).
// The server needs the same for the songbook's PDF (src/songs/songBook.js),
// so this turns those three files into one plain JS module:
//   node scripts/buildSongText.mjs
// Run it again whenever one of the three changes, and commit the result.
import { execSync } from 'child_process';
import esbuild from 'esbuild';

const client = '../client/src/app/pages/daloskonyv';
const outfile = 'src/songs/songText.js';

await esbuild.build({
  stdin: {
    contents: `
      export { parseChordPro, toBlocks, toWords } from './chordpro';
      export { parseChord, transposer, NOTATION } from './chords';
      export { chordShape, uniqueChords } from './chord-shapes';
    `,
    resolveDir: client,
    loader: 'ts',
  },
  bundle: true,
  format: 'esm',
  platform: 'node',
  outfile,
  banner: {
    js: [
      "// GENERATED by scripts/buildSongText.mjs from the client's",
      '// pages/daloskonyv/chordpro.ts, chords.ts and chord-shapes.ts - the',
      '// comments are there. Do not edit: change those and run the script.',
    ].join('\n'),
  },
});
execSync(`npx prettier --write ${outfile} --ignore-path ../.prettierignore`, { stdio: 'inherit' });
console.log(`✓ ${outfile}`);
