name: Server CI

on:
  push:
    branches:
      - main
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: ./server

jobs:
  testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps
        with:
          caching: 'false'

      - name: Output information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test
