name: Server CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'server/**'

jobs:
  testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load and cache dependencies
        id: cache-deps
        uses: ./.github/actions/cached-deps

      - name: Output caching information
        run: echo "Cache used? ${{ steps.cache-deps.outputs.used-cache }}"

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test
